## Упражнения по библиотеке Numpy

In [5]:
import numpy as np
import random

**1.** Дан случайный массив, поменять знак у элементов, значения которых между 3 и 8

In [6]:
array = np.random.randint(0, 10, size=(3, 4))
print(array.ndim)
print(array.shape)
print(array)
array2=np.where((array > 3) & (array < 8), -array, array )
print(array2)

2
(3, 4)
[[1 1 0 8]
 [8 6 7 3]
 [9 5 2 9]]
[[ 1  1  0  8]
 [ 8 -6 -7  3]
 [ 9 -5  2  9]]


**2.** Заменить максимальный элемент случайного массива на 0

In [7]:
array = np.random.randint(1, 100, size=(3, 3))
print(array)

array[array == array.max()]=0
print(array)



[[56  6 64]
 [83 14 11]
 [ 7 87  3]]
[[56  6 64]
 [83 14 11]
 [ 7  0  3]]


**3.** Построить прямое произведение массивов (все комбинации с каждым элементом). На вход подается двумерный массив

In [8]:
array = np.random.randint(1, 100, size=(2, 2))
print(array)

# alone
array2 = array.reshape(-1)
result=[]
for x in array2:
    for y in array2:
        result.append([x, y])

print(result)

result = np.array(result)
print(result)
print(result.shape)

#with chatgpt
x, y = np.meshgrid(array2, array2)

result2 = np.column_stack((x.ravel(), y.ravel()))

print("chatgpt")
print(result2)
print(result2.shape)

[[58 70]
 [57 73]]
[[np.int32(58), np.int32(58)], [np.int32(58), np.int32(70)], [np.int32(58), np.int32(57)], [np.int32(58), np.int32(73)], [np.int32(70), np.int32(58)], [np.int32(70), np.int32(70)], [np.int32(70), np.int32(57)], [np.int32(70), np.int32(73)], [np.int32(57), np.int32(58)], [np.int32(57), np.int32(70)], [np.int32(57), np.int32(57)], [np.int32(57), np.int32(73)], [np.int32(73), np.int32(58)], [np.int32(73), np.int32(70)], [np.int32(73), np.int32(57)], [np.int32(73), np.int32(73)]]
[[58 58]
 [58 70]
 [58 57]
 [58 73]
 [70 58]
 [70 70]
 [70 57]
 [70 73]
 [57 58]
 [57 70]
 [57 57]
 [57 73]
 [73 58]
 [73 70]
 [73 57]
 [73 73]]
(16, 2)
chatgpt
[[58 58]
 [70 58]
 [57 58]
 [73 58]
 [58 70]
 [70 70]
 [57 70]
 [73 70]
 [58 57]
 [70 57]
 [57 57]
 [73 57]
 [58 73]
 [70 73]
 [57 73]
 [73 73]]
(16, 2)


**4.** Даны 2 массива A (8x3) и B (2x2). Найти строки в A, которые содержат элементы из каждой строки в B, независимо от порядка элементов в B

In [9]:
A = np.random.randint(1, 10, size=(8, 3))
print(A)
B = np.random.randint(1,10, size=(2, 2))
print(B)
result = []

for x in A:
    if all(any(element in x for element in y) for y in B):
        result.append(x)
result = np.array(result)
print(f"result:\n {result}")
            
        

[[1 2 8]
 [2 6 5]
 [8 6 6]
 [1 6 3]
 [5 4 1]
 [6 3 1]
 [5 5 5]
 [5 9 2]]
[[6 9]
 [2 8]]
result:
 [[2 6 5]
 [8 6 6]
 [5 9 2]]


**5.** Дана 10x3 матрица, найти строки из неравных значений (например строка [2,2,3] остается, строка [3,3,3] удаляется)

In [10]:
array = np.random.randint(1, 3, (10,3))
print(array)

result = []
for row in array:
    if not (row == row[0]).all():
        result.append(row)
 
result = np.array(result)
print(f"result: \n{result}")

[[2 1 2]
 [2 1 2]
 [2 2 1]
 [1 2 2]
 [2 1 1]
 [1 2 1]
 [1 1 2]
 [1 2 2]
 [2 2 1]
 [2 2 1]]
result: 
[[2 1 2]
 [2 1 2]
 [2 2 1]
 [1 2 2]
 [2 1 1]
 [1 2 1]
 [1 1 2]
 [1 2 2]
 [2 2 1]
 [2 2 1]]


**6.** Дан двумерный массив. Удалить те строки, которые повторяются

In [11]:
array = np.random.randint(0, 2, size=(10, 2))
print(array)

result = np.unique(array, axis=0)

print(f"result: \n {result}")

[[0 1]
 [0 1]
 [1 0]
 [0 1]
 [1 0]
 [1 0]
 [1 1]
 [0 1]
 [0 0]
 [0 1]]
result: 
 [[0 0]
 [0 1]
 [1 0]
 [1 1]]


______
______

Для каждой из следующих задач (1-5) нужно привести 2 реализации – одна без использования numpy (cчитайте, что там, где на входе или выходе должны быть numpy array, будут просто списки), а вторая полностью векторизованная с использованием numpy (без использования питоновских циклов/map/list comprehension).


__Замечание 1.__ Можно считать, что все указанные объекты непустые (к примеру, в __задаче 1__ на диагонали матрицы есть ненулевые элементы).

__Замечание 2.__ Для большинства задач решение занимает не больше 1-2 строк.

* __Задача 1__: Подсчитать произведение ненулевых элементов на диагонали прямоугольной матрицы.  
 Например, для X = np.array([[1, 0, 1], [2, 0, 2], [3, 0, 3], [4, 4, 4]]) ответ 3.

In [12]:
# No NumPy
X = [
    [1, 0, 1],
    [2, 0, 2],
    [3, 0, 3],
    [4, 4, 4]
]

result = 1

for i in range(min(len(X), len(X[0]))):
    if X[i][i] != 0:
        result *= X[i][i]

print(result)


# NumPy
X = np.array([
    [1, 0, 1],
    [2, 0, 2],
    [3, 0, 3],
    [4, 4, 4]
])

d = np.diag(X)
result = np.prod(d[d != 0])

print(result)

3
3


* __Задача 2__: Даны два вектора x и y. Проверить, задают ли они одно и то же мультимножество.  
  Например, для x = np.array([1, 2, 2, 4]), y = np.array([4, 2, 1, 2]) ответ True.

In [13]:
x = np.array([1, 2, 2, 4])
y = np.array([4, 2, 1, 2])
# No NumPy
x = [1, 2, 2, 4]
y = [4, 2, 1, 2]

print(sorted(x) == sorted(y))

#Num Py
x = np.array([1, 2, 2, 4])
y = np.array([4, 2, 1, 2])

result = np.array_equal(np.sort(x), np.sort(y))
print(result)



True
True


* __Задача 3__: Найти максимальный элемент в векторе x среди элементов, перед которыми стоит ноль. 
 Например, для x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0]) ответ 5.

In [14]:
x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0]) 

result = []
for i in range(1, len(x)):
    if x[i - 1] == 0:
        result.append(x[i])

print(max(result))

#gpt NumPy
result = np.amax(x[1:][x[:-1]==0])
print(result)

5
5


* __Задача 4__: Реализовать кодирование длин серий (Run-length encoding). Для некоторого вектора x необходимо вернуть кортеж из двух векторов одинаковой длины. Первый содержит числа, а второй - сколько раз их нужно повторить.  
 Например, для x = np.array([2, 2, 2, 3, 3, 3, 5]) ответ (np.array([2, 3, 5]), np.array([3, 3, 1])).

In [15]:
#No NumPy
x = [4, 4, 1, 1, 1, 7, 7, 4]
counts=[]
ammount=[]
for element in x:
    if counts:
        if counts[-1]==element:
            ammount[-1]+=1
        else:
            counts.append(element)
            ammount.append(1)
    else: 
        counts.append(element)
        ammount.append(1)


result = (counts, ammount)
print("My result:")
print(result)
# numpy gpt
x = np.array([4, 4, 1, 1, 1, 7, 7, 4])

changes = np.where(x[1:] != x[:-1])[0]+1

starts = np.r_[0, changes]
ends = np.r_[changes, len(x)]

length_of = ends - starts
values = x[starts]

resultgpt = (values, length_of)
print(f"resultgpt: \n {resultgpt}")



My result:
([4, 1, 7, 4], [2, 3, 2, 1])
resultgpt: 
 (array([4, 1, 7, 4]), array([2, 3, 2, 1]))


* __Задача 5__: Даны две выборки объектов - X и Y. Вычислить матрицу евклидовых расстояний между объектами. Сравните с функцией scipy.spatial.distance.cdist по скорости работы.

In [16]:
import math
from scipy.spatial.distance import cdist
# No NumPy
X = [
    [0, 0],
    [3, 4]
]

Y = [
    [0, 4],
    [3, 0],
    [6, 8]
]

def my_distance(X, Y):
    result = [[0] * len(Y) for _ in range(len(X))]

    a = 0
    b = 0

    for x in X:
        for y in Y:
            distance = 0

            for i in range(len(x)):
                distance += (y[i] - x[i]) ** 2

            result[a][b] = math.sqrt(distance)
            b += 1

        b = 0
        a += 1

    return result


print(my_distance(X, Y))



# NumPy

X = np.array([
    [0, 0],
    [3, 4]
])

Y = np.array([
    [0, 4],
    [3, 0],
    [6, 8]
])


def numpy_distance(X, Y):
    return np.sqrt(np.sum((X[:, np.newaxis, :] - Y) ** 2, axis=2))


print(numpy_distance(X, Y))
print(cdist(X, Y))
print(np.allclose(numpy_distance(X, Y), cdist(X, Y)))



# Speed test

X_big = np.random.random((1000, 10))
Y_big = np.random.random((1000, 10))

X_big_list = X_big.tolist()
Y_big_list = Y_big.tolist()

%timeit my_distance(X_big_list, Y_big_list)
%timeit numpy_distance(X_big, Y_big)
%timeit cdist(X_big, Y_big)

# Python: 3.34 s
# NumPy: 136 ms
# scipy.spatial.distance.cdist: 11.4 ms
#
# NumPy примерно в 24.6 раза быстрее Python.
# cdist примерно в 11.9 раза быстрее NumPy.
# cdist примерно в 293 раза быстрее Python.

[[4.0, 3.0, 10.0], [3.0, 4.0, 5.0]]
[[ 4.  3. 10.]
 [ 3.  4.  5.]]
[[ 4.  3. 10.]
 [ 3.  4.  5.]]
True
3.28 s ± 485 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
148 ms ± 18.6 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
14.9 ms ± 3.91 ms per loop (mean ± std. dev. of 7 runs, 100 loops each)


_______
________

* #### __Задача 6__: CrunchieMunchies __*__

Вы работаете в отделе маркетинга пищевой компании MyCrunch, которая разрабатывает новый вид вкусных, полезных злаков под названием **CrunchieMunchies**.

Вы хотите продемонстрировать потребителям, насколько полезны ваши хлопья по сравнению с другими ведущими брендами, поэтому вы собрали данные о питании нескольких разных конкурентов.

Ваша задача - использовать вычисления Numpy для анализа этих данных и доказать, что ваши **СrunchieMunchies** - самый здоровый выбор для потребителей.


In [17]:
import numpy as np

1. Просмотрите файл cereal.csv. Этот файл содержит количества калорий для различных марок хлопьев. Загрузите данные из файла и сохраните их как calorie_stats.

In [18]:
calorie_stats = np.loadtxt("./data/cereal.csv", delimiter=",")
calorie_stats

array([ 70., 120.,  70.,  50., 110., 110., 110., 130.,  90.,  90., 120.,
       110., 120., 110., 110., 110., 100., 110., 110., 110., 100., 110.,
       100., 100., 110., 110., 100., 120., 120., 110., 100., 110., 100.,
       110., 120., 120., 110., 110., 110., 140., 110., 100., 110., 100.,
       150., 150., 160., 100., 120., 140.,  90., 130., 120., 100.,  50.,
        50., 100., 100., 120., 100.,  90., 110., 110.,  80.,  90.,  90.,
       110., 110.,  90., 110., 140., 100., 110., 110., 100., 100., 110.])

2. В одной порции CrunchieMunchies содержится 60 калорий. Насколько выше среднее количество калорий у ваших конкурентов?

Сохраните ответ в переменной average_calories и распечатайте переменную в терминале

In [19]:
average_calories = np.average(calorie_stats)
print(f"{(average_calories):.2f}")
print(f"Difference is: {(average_calories-60):.2f}")

106.88
Difference is: 46.88


3. Корректно ли среднее количество калорий отражает распределение набора данных? Давайте отсортируем данные и посмотрим.

Отсортируйте данные и сохраните результат в переменной calorie_stats_sorted. Распечатайте отсортированную информацию

In [20]:
calorie_stats_sorted = np.sort(calorie_stats)
print(calorie_stats_sorted)

#no, we have to use median

[ 50.  50.  50.  70.  70.  80.  90.  90.  90.  90.  90.  90.  90. 100.
 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100.
 100. 100. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110.
 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110.
 110. 110. 110. 120. 120. 120. 120. 120. 120. 120. 120. 120. 120. 130.
 130. 140. 140. 140. 150. 150. 160.]


4. Похоже, что большинство значений выше среднего. Давайте посмотрим, является ли медиана наиболее корректным показателем набора данных.

Вычислите медиану набора данных и сохраните свой ответ в median_calories. Выведите медиану, чтобы вы могли видеть, как она сравнивается со средним значением.

In [21]:
median_calories = np.median(calorie_stats)
print(f"median: {median_calories}")

median: 110.0


5. В то время как медиана показывает, что по крайней мере половина наших значений составляет более 100 калорий, было бы более впечатляюще показать, что значительная часть конкурентов имеет более высокое количество калорий, чем CrunchieMunchies.

Рассчитайте различные процентили и распечатайте их, пока не найдете наименьший процентиль, превышающий 60 калорий. Сохраните это значение в переменной nth_percentile.

In [22]:
percentil1 = np.percentile(calorie_stats, 0)
percentil2 = np.percentile(calorie_stats, 3)
percentil3 = np.percentile(calorie_stats, 5)
percentil4 = np.percentile(calorie_stats, 4)
nth_percentile = percentil4
percentil5 = np.percentile(calorie_stats, 3.5)
percentil6 = np.percentile(calorie_stats, 3.2)
percentil7 = np.percentile(calorie_stats, 3.3)
percentil8 = np.percentile(calorie_stats, 3.25)
percentil9 = np.percentile(calorie_stats, 3.275)
percentil10 = np.percentile(calorie_stats, 3.2899)
print(percentil1)
print(percentil2)
print(percentil3)
print(percentil4)
print(percentil5)
print(percentil6)
print(percentil7)
print(percentil8)
print(percentil9)
print(percentil10)
print(nth_percentile)



50.0
55.599999999999994
70.0
70.0
63.2
58.64
60.16
59.400000000000006
59.78
60.006479999999996
70.0


6. Хотя процентиль показывает нам, что у большинства конкурентов количество калорий намного выше, это неудобная концепция для использования в маркетинговых материалах.

Вместо этого давайте подсчитаем процент хлопьев, в которых содержится более 60 калорий на порцию. Сохраните свой ответ в переменной more_calories и распечатайте его

In [23]:
more_calories = len(calorie_stats[calorie_stats>60])/len(calorie_stats)*100
print(f"more_calories: {more_calories:.2f}%")

more_calories: 96.10%


7. Это действительно высокий процент. Это будет очень полезно, когда мы будем продвигать CrunchieMunchies. Но один вопрос заключается в том, насколько велики различия в наборе данных? Можем ли мы сделать обобщение, что в большинстве злаков содержится около 100 калорий или разброс еще больше?

Рассчитайте величину отклонения, найдя стандартное отклонение, Сохраните свой ответ в calorie_std и распечатайте на терминале. Как мы можем включить эту ценность в наш анализ?

In [24]:
calorie_std = np.std(calorie_stats)
print(calorie_std)
print("Shows")
print(np.average(calorie_stats))
print(f"+- {calorie_std}")


#Стандартное отклонение показывает, насколько сильно значения обычно разбросаны вокруг среднего.

19.35718533390827
Shows
106.88311688311688
+- 19.35718533390827


8. Напишите короткий абзац, в котором кратко изложите свои выводы и то, как, по вашему мнению, эти данные могут быть использованы в интересах Mycrunch при маркетинге CrunchieMunchies.

In [25]:
print(
    "CrunchieMunchies можно позиционировать как одни из самых низкокалорийных\n"
    "хлопьев среди конкурентов. Одна порция содержит всего 60 калорий, что\n"
    "примерно на 46–47 калорий меньше среднего показателя, а медианная\n"
    "калорийность других хлопьев составляет 110 калорий.\n\n"
    "Кроме того, около 96% хлопьев в наборе данных содержат более 60 калорий\n"
    "на порцию. Это позволяет Mycrunch использовать низкую калорийность не\n"
    "только в рекламных материалах, но и как основу нишевой маркетинговой\n"
    "стратегии, ориентированной на потребителей, которые специально ищут\n"
    "низкокалорийные продукты.\n\n"
    "Показатель в 60 калорий может стать сильным УТП (уникальным торговым\n"
    "предложением) CrunchieMunchies и использоваться для четкого\n"
    "позиционирования продукта относительно большинства конкурентов."
)

CrunchieMunchies можно позиционировать как одни из самых низкокалорийных
хлопьев среди конкурентов. Одна порция содержит всего 60 калорий, что
примерно на 46–47 калорий меньше среднего показателя, а медианная
калорийность других хлопьев составляет 110 калорий.

Кроме того, около 96% хлопьев в наборе данных содержат более 60 калорий
на порцию. Это позволяет Mycrunch использовать низкую калорийность не
только в рекламных материалах, но и как основу нишевой маркетинговой
стратегии, ориентированной на потребителей, которые специально ищут
низкокалорийные продукты.

Показатель в 60 калорий может стать сильным УТП (уникальным торговым
предложением) CrunchieMunchies и использоваться для четкого
позиционирования продукта относительно большинства конкурентов.
